### ISSUE TITLE
Access local figure for .main-img-left or .main-img-right

### ISSUE THREAD

**Issue by joshuawlambert** [brentthorne/posterdown#119]
I'm trying to use a .png file within a sub-directory of my posterdown project. Unfortunately, I can't seem to get the poster to knit with the figure. I am working on Rstudio Server and am using the CRAN version of posterdown. 

Here is what I am using:

---
title: "Example"
author:
  - name: Josh
column_numbers: 3
logoleft_name: '![](tmp.png){.main-img-left}'
output: 
  posterdown::posterdown_html:
    self_contained: false
bibliography: packages.bib
---

Thank you.

**Comment by joshuawlambert** [comment]
Update:

Installed latest version of pandoc and updated posterdown to github version. Still no luck. Going from posterdown_html to posterdown_betterland fixes the issue, although I do not want to use that layout. In the mean time, I uploaded the picture to my github and am using the url to access the file.

**Comment by brentthorne** [comment]
Hi @joshuawlambert thanks for using posterdown!

I found a sneaky unwanted space for the posterdown_html left logo implamentation and have fixed it [here](https://github.com/brentthorne/posterdown/commit/82b625f9f09c7b8b661b18769204fb09b5daa2b6#).

Thanks for the heads up on this and please let me know if this worked out for you!

Cheers!

**Comment by allan296** [comment]
I had the same problem, but with "betterport" output. I cant't use local images and I don't know how to limit the logo size, because in betterland template the logo is too big. Sorry if here isn't the right place for this question.
````
---
title: "Example"
author:
  - name: Josh
column_numbers: 3
logoleft_name: '![](tmp.png){.main-img-left}'
logoright_name: "![](figures/logo.png)"
output: 
  posterdown::posterdown_betterport:
    self_contained: false
bibliography: packages.bib
---
```
