### ISSUE TITLE
Email and Twitter handle don't change font size in posterdown_betterport

### ISSUE THREAD

**Issue by monicathieu** [brentthorne/posterdown#120]
First off, **THANK YOU** for developing and maintaining this package, it fills a long-standing need for me :)

1. I used `posterdown_betterport` but I suspect that this applies to `posterdown_betterland` as well.
2. System versions: Mac OS X Mojave, R 3.6.1, RStudio 1.1.442

3. Package version: 1.0, GitHub (downloaded a few weeks ago)
4. I notice that when I set lead author email and Twitter handle in the YAML header, the email address/Twitter username do not seem to obey the font size set in `affiliation_textsize`, `author_textsize`, `authorextra_textsize`, or `body_textsize`. To debug, if I set them all to:
```
---
author:
  - name: '**Monica Thieu**'
    affil: 1
    main: true
    twitter: monica_too_
    email: monica.thieu@columbia.edu
  - name: My Advisor
    affil: 1
    main: true
affiliation:
  - num: 1
    address: My Dept, My University
author_textsize: "18pt"
authorextra_textsize: "18pt"
affiliation_textsize: "18pt"
body_textsize: "18pt"
poster_height: "30in"
poster_width: "18in"
---
```
the clickable email address and Twitter handle are still rendering larger than the author names, maybe 20-something point font. They DO appear to scale with the poster height and width, but that might just be differences in the relative size of the words on the poster overall.

I figure that somewhere in the code the appropriate text size YAML variable is not feeding forward into the code that actually renders the Twitter and email info. Hopefully it's a quick fix!
