### ISSUE TITLE
How to render posterdown_html template as a pdf

### ISSUE THREAD

**Issue by tanga94** [brentthorne/posterdown#129]
Is there a way to generate then ```posterdown_html``` template as a PDF instead of the default HTML format that is generated?

Additionally, what is the best way to change the default color in the header and titles from green to a different color (HTML color code)?

I'm using RStudio, and here is the default YAML that is generated when I download the template I'm interested in using

```
---
title: Generate Reproducible & Live HTML and PDF Conference Posters Using RMarkdown
author:
  - name: Brent Thorne
    affil: 1
    orcid: '0000-0002-1099-3857'
  - name: Another G. Author
    affil: 2
affiliation:
  - num: 1
    address: Department of Earth Science, Brock University
  - num: 2
    address: Department of Graphics and Layouts, University of Posters; Canada
column_numbers: 3
logoright_name: https&#58;//raw.githubusercontent.com/brentthorne/posterdown/master/images/betterhexlogo.png
logoleft_name: https&#58;//raw.githubusercontent.com/brentthorne/posterdown/master/images/betterhexlogo.png
output: 
  posterdown::posterdown_html:
    self_contained: false
bibliography: packages.bib
---


```
