### ISSUE TITLE
Can't change bibliography/reference text size in posterdown_html 

### ISSUE THREAD

**Issue by buveges** [brentthorne/posterdown#132]
I can't seem to change the text size of the reference/bibliography section in my posterdown_html "classic scientific poster" output. I have tried bibliography_textsize, and reference_textsize, nothing changes. I see in the classic poster example the references are smaller text size, so I am not sure what I am doing wrong here. The issue appears in the example .Rmd and any new .Rmd doc I create. Any help is greatly appreciated.

Example header with text size argument included.

```
title: Generate Reproducible & Live HTML and PDF Conference Posters Using RMarkdown
author:
  - name: Brent Thorne
    affil: 1
    orcid: '0000-0002-1099-3857'
  - name: Another G. Author
    affil: 2
affiliation:
  - num: 1
    address: Department of Earth Science, Brock University
  - num: 2
    address: Department of Graphics and Layouts, University of Posters; Canada
column_numbers: 3
logoright_name: https&#58;//raw.githubusercontent.com/brentthorne/posterdown/master/images/betterhexlogo.png
logoleft_name: https&#58;//raw.githubusercontent.com/brentthorne/posterdown/master/images/betterhexlogo.png
bibliography: packages.bib
bibliography_textsize: "10pt"
output: 
  posterdown::posterdown_html:
    self_contained: false
```
