### ISSUE TITLE
More than two affilliations

### ISSUE THREAD

**Issue by mckenziephagen** [brentthorne/posterdown#145]
Template: posterdown_html

OS: Mac M1, 13.4.1 
R: R version 4.3.3 (2024-02-29) -- "Angel Food Cake"

Posterdown: CRAN 

Issue: 
I have a lengthy author list, with collaborators from three different schools/departments. Only the first two show up.  I made the affiliation_textsize small, and then I could see a the very top of the third affiliation, but the majority that hangs off of the header rectangle is chopped off. See attached pdf. 

How can I make the affiliations wrap, rather than stack on top of each other? 

yml block: 
```
---
title: Evaluating Accuracy and Reliability of Brain-Behavior Models Using Diffusion MRI 
author:
  - name: McKenzie Paige Hagen
    affil: 1
    orcid: '0000-0002-1099-3857' #TODO
  - name: John Kruper
    affil: 1
  - name: Keshav Motwani 
    affil: 2
  - name: Eardi Lila
    affil: 2
  - name: Jason Yeatman
    affil: 3
  - name: Ariel Rokem
    affil: 1
affiliation:
  - num: 1
    address: Department of Psychology, University of Washington
  - num: 2
    address: Department of Biostatistics, University of Washington
  - num: 3
    address: Graduate School of Education, Stanford University
 
column_numbers: 3
#logoright_name: #https&#58;//raw.githubusercontent.com/brentthorne/posterdown/master/images/betterhexlogo.png
#logoleft_name: #https&#58;//raw.githubusercontent.com/brentthorne/posterdown/master/images/betterhexlogo.png
output: 
  posterdown::posterdown_html:
    self_contained: true
bibliography: packages.bib
---
```
rendered pdf using `pagedown::chrome_print("poster_draft.Rmd")`: 
[poster_draft.pdf](https://github.com/brentthorne/posterdown/files/15257582/poster_draft.pdf)

Thanks!
